# Generated by Django 2.2.9 on 2020-01-19 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateField(blank=True, verbose_name='fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='semester',
            field=models.CharField(blank=True, choices=[('1', 'Primero'), ('2', 'Segundo'), ('3', 'Tercero'), ('4', 'Cuarto'), ('5', 'Quinto'), ('6', 'Sexto'), ('7', 'Séptimo'), ('8', 'Octavo'), ('9', 'Noveno'), ('10', 'Décimo'), ('11', 'Onceavo'), ('12', 'Doceavo')], max_length=1, verbose_name='semestre'),
        ),
    ]
