# Generated by Django 2.2.9 on 2020-02-17 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='egress',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='user_id',
        ),
    ]
