# Generated by Django 2.2.9 on 2020-02-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20200217_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egress',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Monto'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Monto'),
        ),
    ]
