# Generated by Django 2.2.9 on 2020-02-24 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_auto_20200217_1135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='egress',
            options={'ordering': ['-id'], 'verbose_name': 'Gasto', 'verbose_name_plural': 'Gastos'},
        ),
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-id'], 'verbose_name': 'Ingreso', 'verbose_name_plural': 'Ingresos'},
        ),
    ]
